service: lambda-webpack

frameworkVersion: '3.21.0'


provider:
  name: aws
  runtime: nodejs12.x
  # lambdaHashingVersion: '20201221'
  region: us-east-2

functions:
  my-test:
    handler: src/handler.handler
    # events:
    #   - http:
    #       path: /
    #       method: get
